services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    dns:
      - 8.8.8.8
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules  # Avoid overwriting node_modules
    depends_on:
      - backend
    